# Description: runtime environment for container on kali
# Usage info goes here  -- add words ---

# setup the image to use
FROM ubuntu

# have to set to non-interactive so it doesn't try to get user input
ENV DEBIAN_FRONTEND noninteractive

# setup environment for systemd
ENV container docker

# update upgrade
RUN apt-get update
RUN apt-get upgrade -y


# install some useful tools
RUN apt-get install sudo iputils-ping net-tools nano vim-y
RUN apt-get install software-properties-common -y
RUN apt-get install systemd systemd-sysv -y
RUN apt-get install apt-utils -y

# setup ssh / x11 depend
RUN apt-get install openssh-server -y
# make it so the ssh server starts automatically
RUN sudo update-rc.d ssh defaults
# RUN systemctl start ssh.service #can't do this -- this is an image
RUN apt-get install --no-install-recommends xorg lxdm lxqt -y

# we need to add ssh to the initd.conf file so it will start automatically 
RUN echo "telnet                  stream  tcp     nowait  root    /usr/local/libexec/telnetd      telnetd" >> /etc/inetd.conf
RUN echo "telnet                  stream  tcp     nowait  root    /usr/sbin/telnetd      telnetd" >> /etc/inetd.conf
# from reading online this is a bad idea because of time to setup components (keys)... let's see if can do once container is created?

# setup repo and pull down Kodi
# RUN sudo add-apt-repository ppa:team-xmbc/ppa
# RUN sudo apt-get update
RUN apt-get install kodi -y

# create a user and set home directory
RUN useradd -rm -d /home/svruser -s /bin/bash -g root -G sudo svruser
# add a line here about setting the user password
#RUN sudo passwd svruser 
RUN echo "svruser:test1" | chpasswd

# ssh setting
RUN echo "PermitRootLogin yes" >> /etc/ssh/sshd_config
RUN echo "PasswordAuthentication yes" >> /etc/ssh/sshd_config
ENTRYPOINT service ssh start && bash


# let's send some useful information to the user at this point
RUN echo 'now can RUN container: sudo docker run -it --name kodisvr --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro -p 192.168.1.186:2200:22 kosvr'
RUN echo 'once you are in the SSH session then type: kodi'
RUN echo 'Kodi should open and you can now configure the software accordingly'

# Things to verify
# can we create our own user or does it have to be "pi" or one of the root users?
# does this even work


